Doctrine\ORM\Query / Doctrine\ORM\Execption
EC-CUBE/next-poc pull request #45
Opened 2023-06-16 00:26 UTC by chihiro-adachi

## 概要(Overview・Refs Issue)

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-06-20 10:07 UTC, kiy0taka requested changes

2023-06-20 10:07 UTC, kiy0taka commented on src/framework/Eccube/ORM/Exception/ORMException.php
> +    public static function wrapORMException(\Exception $e): ORMException
staticメソッドではなく、コンストラクタで。
```
public function __construct(Doctrine\ORM\Exception\ORMException $e)
```

2023-06-20 10:07 UTC, kiy0taka commented on src/framework/Eccube/ORM/Exception/ORMException.php
> +    public static function wrapForeignKeyException(\Exception $e): ForeignKeyConstraintViolationException
こちらもコンストラクタで。

2023-06-20 10:07 UTC, kiy0taka commented on src/framework/Eccube/ORM/Query.php
> +    public const HYDRATE_OBJECT = 1;
定数値はDoctrineQueryの定数を使用したほうが安全です。
```
public const HYDRATE_OBJECT = DoctrineQuery::HYDRATE_OBJECT;
```

2023-06-20 10:07 UTC, kiy0taka commented on src/framework/Eccube/ORM/Pager/QuerySubscriber.php
> +            $event->target = $query;
`QueryBuilderSubscriber` では `Eccube\ORM\QueryBuilder` -> `Eccube\ORM\Query` に変換していますが、こちらでは `Eccube\ORM\Query` -> `Doctrine\ORM\Query` に変換しているようです。2つのSubscriberで `Eccube\ORM\QueryBuilder` -> `Eccube\ORM\Query` -> `Doctrine\ORM\Query` と変換するのであれば優先度を明示的に分けておくほうが良いかと思います。

2023-06-20 10:07 UTC, kiy0taka commented on src/application/Eccube/Controller/Admin/AdminController.php
> +        } catch (ORMException $e) {
結果がない処理を `ORMException` で受けるのは広すぎるので  `NoResultException` もラッパークラスにしましょう。

2023-06-22 05:36 UTC, chihiro-adachi commented on src/framework/Eccube/ORM/Exception/ORMException.php
> +    public static function wrapORMException(\Exception $e): ORMException
修正しました

2023-06-22 05:36 UTC, chihiro-adachi commented on src/framework/Eccube/ORM/Exception/ORMException.php
> +    public static function wrapForeignKeyException(\Exception $e): ForeignKeyConstraintViolationException
修正しました

2023-06-22 05:36 UTC, chihiro-adachi commented on src/framework/Eccube/ORM/Query.php
> +    public const HYDRATE_OBJECT = 1;
修正しました

2023-06-22 05:37 UTC, chihiro-adachi commented on src/framework/Eccube/ORM/Pager/QuerySubscriber.php
> +            $event->target = $query;
QueryBuilderSubscriber単体でDoctrine\ORM\Queryまで変換するようにしました。

2023-06-22 05:37 UTC, chihiro-adachi commented on src/application/Eccube/Controller/Admin/AdminController.php
> +        } catch (ORMException $e) {
修正しました

2023-06-23 02:48 UTC, kiy0taka approved these changes

2023-06-23 02:48 UTC, merged