Symfony/EventDispatcher
EC-CUBE/next-poc pull request #54
Opened 2023-06-29 08:26 UTC by kiy0taka

## 概要(Overview・Refs Issue)

#40 

## 方針(Policy)

## 実装に関する補足(Appendix)

## テスト（Test)

## 相談（Discussion）

## マイナーバージョン互換性保持のための制限事項チェックリスト

- [ ] 既存機能の仕様変更はありません
- [ ] フックポイントの呼び出しタイミングの変更はありません
- [ ] フックポイントのパラメータの削除・データ型の変更はありません
- [ ] twigファイルに渡しているパラメータの削除・データ型の変更はありません
- [ ] Serviceクラスの公開関数の、引数の削除・データ型の変更はありません
- [ ] 入出力ファイル(CSVなど)のフォーマット変更はありません

## レビュワー確認項目

- [ ] 動作確認
- [ ] コードレビュー
- [ ] E2E/Unit テスト確認(テストの追加・変更が必要かどうか)
- [ ] 互換性が保持されているか
- [ ] セキュリティ上の問題がないか
  - [ ] 権限を超えた操作が可能にならないか
  - [ ] 不要なファイルアップロードがないか
  - [ ] 外部へ公開されるファイルや機能の追加ではないか
  - [ ] テンプレートでのエスケープ漏れがないか

2023-06-30 01:06 UTC, chihiro-adachi requested changes

2023-06-30 01:06 UTC, chihiro-adachi commented on src/framework/Eccube/EventDispatcher/EventSubscriberInterface.php
> +interface EventSubscriberInterface extends \Composer\EventDispatcher\EventSubscriberInterface
@kiy0taka 
ComposerのEventSubscriberInterfaceになってます。

2023-06-30 01:08 UTC, kiy0taka commented on src/framework/Eccube/EventDispatcher/EventSubscriberInterface.php
> +interface EventSubscriberInterface extends \Composer\EventDispatcher\EventSubscriberInterface
@chihiro-adachi 修正しておきました！

2023-07-04 22:58 UTC, chihiro-adachi approved these changes

2023-07-05 00:33 UTC, merged